#Application properties
server:
  port: 8080
  ssl:
      enabled: true
      key-alias: samplekey
      key-store: classpath:samplekey.p12
      key-store-type: PKCS12
      key-password: sathish
      key-store-password: sathish
      
      

#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
#      accessKey: AKIA32CIHYHAOT2KHV
#      secretKey: fcmvvq1hcDoSWmHSem6VRc6GdHw2081lUawajH
      accessKey: AKIAZHD3NVT43QHEQW5K
      secretKey: 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

application:
  bucket:
    name: sathishkumartest
#application:
#  bucket:
#    name: techgeeknextbucket

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
          

